### ISSUE TITLE
time_diff says that some translations were submitted "in 3 hours" on live site

### ISSUE THREAD

**Issue by trvshrmn** [trvshrmn/CrossDocs#26]
maybe it only happens when i imported my MAMP database to the live site.

**Comment by derekdavenport** [comment]
Try this:
https://stackoverflow.com/questions/10955563/storing-doctrine2-datetime-in-utc-only

**Comment by trvshrmn** [comment]
Do we really need to fix anything? This line is how stuff has been getting imported into the live site: 

```
INSERT INTO  `translation` (  `id` ,  `document_part_id` ,  `text` ,  `comment` ,  `author_id` ,  `date` ,  `language_code` ) 
VALUES ( 169, 1,  'time_test2', NULL , 1,  '2016-03-08 15:03:12',  'hi' )
```

But those values were created on my local server... In reality we shouldn't ever import data into the live site database that was created on our local servers.
